// Code generated by nibgen. DO NOT EDIT.
// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>

// Nib 运行时 shim：错误信封与 IPC 调用封装。
// stream/subscribe 为 M4 桩：类型与协议已定，运行时尚未实现（调用即抛 ipc/not_implemented）。

export interface NibErrorFrame {
  layer: 'js' | 'ipc' | 'go';
  frame?: string; // 代码位置，如 fs_service.go:88 os.Open
  call?: string; // IPC 调用名
  extra?: Record<string, unknown>;
}

export interface NibErrorEnvelope {
  code: string; // 如 fs.read/permission_denied
  message: string;
  chain?: NibErrorFrame[]; // JS → IPC → Go 因果链（M2 诊断填充）
  retryable: boolean;
  doc?: string;
}

export class NibError extends Error {
  code: string;
  chain?: NibErrorFrame[];
  retryable: boolean;
  doc?: string;

  constructor(env: NibErrorEnvelope) {
    super(env.message);
    this.name = 'NibError';
    this.code = env.code;
    this.chain = env.chain;
    this.retryable = env.retryable;
    this.doc = env.doc;
  }
}

interface NibBridge {
  invoke(call: string, args?: unknown): Promise<unknown>;
}

function bridge(): NibBridge {
  const b = (window as { nib?: NibBridge }).nib;
  if (!b) {
    throw new NibError({ code: 'ipc/no_bridge', message: 'window.nib 未注入（非 Nib WebView 环境？）', retryable: false });
  }
  return b;
}

/** 把桥 reject 的裸信封对象规范化为 NibError。 */
function toNibError(e: unknown): NibError {
  if (e instanceof NibError) return e;
  if (typeof e === 'object' && e !== null && typeof (e as { code?: unknown }).code === 'string') {
    return new NibError(e as NibErrorEnvelope);
  }
  return new NibError({ code: 'ipc/unknown', message: String(e), retryable: false });
}

/** 请求-响应调用；错误以 NibError 抛出。 */
export async function call<R>(method: string, args?: unknown): Promise<R> {
  try {
    return (await bridge().invoke(method, args ?? null)) as R;
  } catch (e) {
    throw toNibError(e);
  }
}

/** 双向流（M4）：类型已生成，运行时尚未实现。 */
export async function* stream<T>(method: string, args?: unknown): AsyncGenerator<T> {
  void method; void args;
  throw new NibError({ code: 'ipc/not_implemented', message: 'stream IPC 将于 M4 落地', retryable: false });
  yield* [] as T[];
}

/** 事件订阅（M4）：类型已生成，运行时尚未实现。 */
export function subscribe<T>(method: string, cb: (event: T) => void): () => void {
  void method; void cb;
  throw new NibError({ code: 'ipc/not_implemented', message: 'event IPC 将于 M4 落地', retryable: false });
}
