// Code generated by nibgen. DO NOT EDIT.
// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>

export interface Base { id: number }

export interface GreetArgs { name: string; tags?: string[]; createdAt: string }

export interface GreetResult { message: string; meta: Record<string, string>; extra: GreetArgs | null }

export type Status = string;

