package binding

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Report 是一次生成的结果：写盘 / 未变 / 清理的文件清单。
type Report struct {
	Written   []string
	Unchanged []string
	Removed   []string
}

// Generate 把解析结果写成 TS 客户端到 outDir：
//
//	nib.ts              运行时 shim（call + NibError；stream/subscribe 为 M4 桩）
//	types.ts            命名结构体的共享 interface（引用到时才生成）
//	services/<Svc>.ts   每个服务一个客户端文件
//	index.ts            汇总导出
//
// 内容未变的文件不写盘；输出目录中已不存在的服务文件会被清理。
func Generate(pkg *Package, outDir string) (*Report, error) {
	if err := cleanDir(outDir); err != nil {
		return nil, err
	}
	rep := &Report{}
	structNames := map[string]bool{}
	for _, st := range pkg.Structs {
		structNames[st.Name] = true
	}
	files := map[string]string{
		"nib.ts":   runtimeShim,
		"index.ts": renderIndex(pkg),
	}
	if len(pkg.Structs) > 0 {
		files["types.ts"] = renderTypes(pkg)
	}
	for _, svc := range pkg.Services {
		files[filepath.Join("services", svc.Name+".ts")] = renderService(svc, structNames)
	}

	for name, content := range files {
		status, err := writeIfChanged(filepath.Join(outDir, name), content)
		if err != nil {
			return nil, err
		}
		if status == "written" {
			rep.Written = append(rep.Written, name)
		} else {
			rep.Unchanged = append(rep.Unchanged, name)
		}
	}

	// 清理已删除服务的残留文件。
	entries, err := os.ReadDir(filepath.Join(outDir, "services"))
	if err != nil {
		return nil, err
	}
	keep := map[string]bool{}
	for _, svc := range pkg.Services {
		keep[svc.Name+".ts"] = true
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".ts") && !keep[e.Name()] {
			if err := os.Remove(filepath.Join(outDir, "services", e.Name())); err != nil {
				return nil, err
			}
			rep.Removed = append(rep.Removed, filepath.Join("services", e.Name()))
		}
	}
	sort.Strings(rep.Written)
	sort.Strings(rep.Unchanged)
	sort.Strings(rep.Removed)
	return rep, nil
}

// writeIfChanged 内容相同则跳过，返回 "written" / "unchanged"。
func writeIfChanged(path, content string) (string, error) {
	if b, err := os.ReadFile(path); err == nil && string(b) == content {
		return "unchanged", nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("写 %s: %w", path, err)
	}
	return "written", nil
}

const header = "// Code generated by nibgen. DO NOT EDIT.\n// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>\n\n"

// renderService 生成单个服务的客户端。
func renderService(svc Service, structNames map[string]bool) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("import { ")
	kinds := map[Kind]bool{}
	for _, m := range svc.Methods {
		kinds[m.Kind] = true
	}
	var imports []string
	if kinds[KindCall] {
		imports = append(imports, "call")
	}
	if kinds[KindStream] {
		imports = append(imports, "stream")
	}
	if kinds[KindEvent] {
		imports = append(imports, "subscribe")
	}
	b.WriteString(strings.Join(imports, ", "))
	b.WriteString(" } from '../nib';\n")
	if serviceUsesTypes(svc, structNames) {
		b.WriteString("import type * as types from '../types';\n")
	}
	b.WriteString("\nexport const " + svc.Name + " = {\n")
	for _, m := range svc.Methods {
		if m.Doc != "" {
			for _, line := range strings.Split(m.Doc, "\n") {
				b.WriteString("  /** " + line + " */\n")
			}
		}
		fullName := svc.Name + "." + m.Name
		switch m.Kind {
		case KindCall:
			fmt.Fprintf(&b, "  %s(%s): Promise<%s> {\n", m.Name, paramList(m.Params, structNames), qualify(m.Result, structNames))
			if len(m.Params) == 0 {
				fmt.Fprintf(&b, "    return call<%s>('%s');\n", qualify(m.Result, structNames), fullName)
			} else {
				fmt.Fprintf(&b, "    return call<%s>('%s', { %s });\n",
					qualify(m.Result, structNames), fullName, argNames(m.Params))
			}
			b.WriteString("  },\n")
		case KindStream:
			fmt.Fprintf(&b, "  async *%s(%s): AsyncGenerator<%s> {\n", m.Name, paramList(m.Params, structNames), qualify(m.Elem, structNames))
			if len(m.Params) == 0 {
				fmt.Fprintf(&b, "    yield* stream<%s>('%s');\n", qualify(m.Elem, structNames), fullName)
			} else {
				fmt.Fprintf(&b, "    yield* stream<%s>('%s', { %s });\n", qualify(m.Elem, structNames), fullName, argNames(m.Params))
			}
			b.WriteString("  },\n")
		case KindEvent:
			fmt.Fprintf(&b, "  %s(cb: (event: %s) => void): () => void {\n", m.Name, qualify(m.Elem, structNames))
			fmt.Fprintf(&b, "    return subscribe<%s>('%s', cb);\n", qualify(m.Elem, structNames), fullName)
			b.WriteString("  },\n")
		}
	}
	b.WriteString("} as const;\n")
	return b.String()
}

// serviceUsesTypes 判断服务的签名是否引用了具名结构体（决定是否 import types）。
func serviceUsesTypes(svc Service, structNames map[string]bool) bool {
	if len(structNames) == 0 {
		return false
	}
	uses := func(ts string) bool { return qualify(ts, structNames) != ts }
	for _, m := range svc.Methods {
		for _, p := range m.Params {
			if uses(p.Type) {
				return true
			}
		}
		if uses(m.Result) || uses(m.Elem) {
			return true
		}
	}
	return false
}

// qualify 给具名结构体引用加 types. 前缀；只替换注册的整词（\b 边界）。
func qualify(ts string, structNames map[string]bool) string {
	if len(structNames) == 0 {
		return ts
	}
	names := make([]string, 0, len(structNames))
	for n := range structNames {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool { return len(names[i]) > len(names[j]) })
	for _, n := range names {
		ts = regexp.MustCompile(`\b`+n+`\b`).ReplaceAllString(ts, "types."+n)
	}
	return ts
}

func paramList(params []Param, structNames map[string]bool) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.Name+": "+qualify(p.Type, structNames))
	}
	return strings.Join(parts, ", ")
}

func argNames(params []Param) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.Name)
	}
	return strings.Join(parts, ", ")
}

// renderTypes 生成共享结构体定义文件。
func renderTypes(pkg *Package) string {
	var b strings.Builder
	b.WriteString(header)
	for _, s := range pkg.Structs {
		if s.Struct {
			b.WriteString("export interface " + s.Name + " { " + s.Body + " }\n\n")
		} else {
			b.WriteString("export type " + s.Name + " = " + s.Body + ";\n\n")
		}
	}
	return b.String()
}

// renderIndex 生成汇总导出。
func renderIndex(pkg *Package) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("export * from './nib';\n")
	if len(pkg.Structs) > 0 {
		b.WriteString("export * from './types';\n")
	}
	for _, svc := range pkg.Services {
		fmt.Fprintf(&b, "export { %s } from './services/%s';\n", svc.Name, svc.Name)
	}
	return b.String()
}

// runtimeShim 是生成物的运行时支撑：错误信封 + call 实现 + stream/event 桩（M4 落地）。
const runtimeShim = header + `// Nib 运行时 shim：错误信封与 IPC 调用封装。
// stream/subscribe 为 M4 桩：类型与协议已定，运行时尚未实现（调用即抛 ipc/not_implemented）。

export interface NibErrorFrame {
  layer: 'js' | 'ipc' | 'go';
  frame?: string; // 代码位置，如 fs_service.go:88 os.Open
  call?: string; // IPC 调用名
  extra?: Record<string, unknown>;
}

export interface NibErrorEnvelope {
  code: string; // 如 fs.read/permission_denied
  message: string;
  chain?: NibErrorFrame[]; // JS → IPC → Go 因果链（M2 诊断填充）
  retryable: boolean;
  doc?: string;
}

export class NibError extends Error {
  code: string;
  chain?: NibErrorFrame[];
  retryable: boolean;
  doc?: string;

  constructor(env: NibErrorEnvelope) {
    super(env.message);
    this.name = 'NibError';
    this.code = env.code;
    this.chain = env.chain;
    this.retryable = env.retryable;
    this.doc = env.doc;
  }
}

interface NibBridge {
  invoke(call: string, args?: unknown): Promise<unknown>;
}

function bridge(): NibBridge {
  const b = (window as { nib?: NibBridge }).nib;
  if (!b) {
    throw new NibError({ code: 'ipc/no_bridge', message: 'window.nib 未注入（非 Nib WebView 环境？）', retryable: false });
  }
  return b;
}

/** 把桥 reject 的裸信封对象规范化为 NibError。 */
function toNibError(e: unknown): NibError {
  if (e instanceof NibError) return e;
  if (typeof e === 'object' && e !== null && typeof (e as { code?: unknown }).code === 'string') {
    return new NibError(e as NibErrorEnvelope);
  }
  return new NibError({ code: 'ipc/unknown', message: String(e), retryable: false });
}

/** 请求-响应调用；错误以 NibError 抛出。 */
export async function call<R>(method: string, args?: unknown): Promise<R> {
  try {
    return (await bridge().invoke(method, args ?? null)) as R;
  } catch (e) {
    throw toNibError(e);
  }
}

/** 双向流（M4）：类型已生成，运行时尚未实现。 */
export async function* stream<T>(method: string, args?: unknown): AsyncGenerator<T> {
  void method; void args;
  throw new NibError({ code: 'ipc/not_implemented', message: 'stream IPC 将于 M4 落地', retryable: false });
  yield* [] as T[];
}

/** 事件订阅（M4）：类型已生成，运行时尚未实现。 */
export function subscribe<T>(method: string, cb: (event: T) => void): () => void {
  void method; void cb;
  throw new NibError({ code: 'ipc/not_implemented', message: 'event IPC 将于 M4 落地', retryable: false });
}
`
