// Code generated by nibgen. DO NOT EDIT.
// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>

import { subscribe } from '../nib';
import type * as types from '../types';

export const BusService = {
  FileChanged(cb: (event: types.GreetArgs) => void): () => void {
    return subscribe<types.GreetArgs>('BusService.FileChanged', cb);
  },
} as const;
