// Code generated by nibgen. DO NOT EDIT.
// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>

import { call } from '../nib';
import type * as types from '../types';

export const GreetService = {
  Check(flag: boolean, raw: unknown): Promise<boolean> {
    return call<boolean>('GreetService.Check', { flag, raw });
  },
  /** Greet 问候。 */
  Greet(args: types.GreetArgs): Promise<types.GreetResult> {
    return call<types.GreetResult>('GreetService.Greet', { args });
  },
  List(ids: number[]): Promise<types.Status[]> {
    return call<types.Status[]>('GreetService.List', { ids });
  },
  Ping(): Promise<string> {
    return call<string>('GreetService.Ping');
  },
  /** StatusOf 返回嵌入结构体（展平）+ 匿名结构体。 */
  StatusOf(base: types.Base): Promise<{ code: number; id: number }> {
    return call<{ code: number; id: number }>('GreetService.StatusOf', { base });
  },
  Sum(a: number, b: number): Promise<number> {
    return call<number>('GreetService.Sum', { a, b });
  },
} as const;
