// Code generated by nibgen. DO NOT EDIT.
// 源码改动后重新运行：go run nib.dev/nib/cmd/nibgen -out <dir> <pkgdir>

import { stream } from '../nib';

export const TaskService = {
  async *RunPipeline(input: string): AsyncGenerator<number> {
    yield* stream<number>('TaskService.RunPipeline', { input });
  },
} as const;
